import scipy.io


def load_sync_parameters(file_name):
    """
    OPENDIRECTION SPECIFIC
    Generated by custom synchronization codes that deal with delay between the
    start of camera and the start of recording and a correction which is
    applied for the recording to deal with drift in the sampling rate over
    long recording periods
    - Delay_Mantis_Spikeglx: Deals with the delay between the start of spike
    recording and the start of camera recording
    - Ratio_Mantis_Spikeglx: Deals with a slow drift in the sampling rate that
    can occur with the spike recording over long experiments.
    It is extracted by aligning some randomly spaced triggers on the spike
    recording software (spikeglx) with the same triggers sent by the arduino
    to the behavior recording software (Mantis).

    :param file_name: Input filename, e.g. sync_parameter.mat
    :return: Drift ratio, Delay
    """
    sync_parameters = scipy.io.loadmat(file_name)
    ratio_mantis_spike = sync_parameters["Ratio_Mantis_SPIKEGLX"]
    delay_mantis_spike = sync_parameters["Delay_Mantis_Spikeglx"]
    return ratio_mantis_spike[0][0], delay_mantis_spike[0][0]
